### ISSUE TITLE
Create textures for the roadway

### ISSUE THREAD

**Issue by beansmyname** [notatroll/godot-jam-june-2016#5]

**Comment by beansmyname** [comment]
Do we want to keep the grid as a grid or have textured tiles?

**Comment by alesegdia** [comment]
To use textured tiles the internal representation must be changed, since it's made up of lines now; it should be made up of triangles then, and check a way to somehow wireframe it to keep sides "illuminated".

In my opinion it looks cool as it's now, but we can keep this in mind in order to check how it looks with textured tiles when more of the core mechanics are done.

**Comment by beansmyname** [comment]
Definitely further down the list of priorities.

**Comment by beansmyname** [comment]
I thought this one was closed? You added the box, right?

**Comment by alesegdia** [comment]
I left this as a future enhancement, but you're right, if we have the box to identify blue quads, this is unnecesary. Closing this.
